version: '3.7'

services:
  redis:
    image: redis
    restart: always
    networks:
        Airflow_network:
            ipv4_address: 172.20.1.2
  mysql:
    image: mysql:8
    command: mysqld --explicit_defaults_for_timestamp=ON
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_USER=airflow
      - MYSQL_ROOT_PASSWORD=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
      - MYSQL_DATABASE=airflow
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
        Airflow_network:
            ipv4_address: 172.20.1.3


  webserver:
    build: .
    #image: airflow-image:latest
    command: wait-for-it mysql:3306 -- bash -c 'airflow db init && airflow webserver'
    depends_on:
      - mysql
      - redis
    restart: always
    ports:
      - 8081:8080
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow:airflow@mysql/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+mysql://airflow:airflow@mysql/airflow
      - AIRFLOW_HOME=/usr/local/airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
    networks:
        Airflow_network:
            ipv4_address: 172.20.1.4


  scheduler:
    build: .
    #image: airflow-image:latest
    command: wait-for-it webserver:8080 -- airflow scheduler
    depends_on:
      - webserver
    restart: always
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow:airflow@mysql/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+mysql://airflow:airflow@mysql/airflow
      - AIRFLOW_HOME=/usr/local/airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
      #- ./logs:/usr/local/airflow/logs
    networks:
        Airflow_network:
            ipv4_address: 172.20.1.5


  worker:
    build: .
    #image: airflow-image:latest
    command: wait-for-it webserver:8082 -- airflow celery worker
    depends_on:
      - scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqldb://airflow:airflow@mysql/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+mysql://airflow:airflow@mysql/airflow
      - AIRFLOW_HOME=/usr/local/airflow
    volumes:
      - ./dags:/usr/local/airflow/dags
    networks:
        Airflow_network:
            ipv4_address: 172.20.1.6


networks:
  Airflow_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.20.1.0/16"
